language: python
python:
  - 3.6
  - nightly
install:
  - pip install -r requirements/dev.txt
script:
  - nosetests --with-cov --cov-config .coveragerc
after_success:
  - codecov
jobs:
  include:
    - stage: Deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: fUNq4pQN00b0e4mnr01RO9riCZS6J4eAPo03cYqVwjJ0Fks6KAMqKrObDe4ddK8D3gywPXdvDHF0o+KUlbdUwN9preEwlHf9Sm59DopJhTK1MxDNtbOtcBJBm0K8UCiME5/UMP0b3b8k2Hyydr8oKtqvGkHLntVwfPPtEO+YFudjS6qu1jh6Wg/58mgoKWocUc6Adp17XNdFspO+Qqy3lIfcj+XNzPDkO2Z0INvAMZmxBVtHtoFBdhLFfLDXgBsFgpRYoYfJFPyPCLur60lE9PhZXrqOXSLFzh0z9ZytlnthFoMXZ1+OALO8XVaG44+bhX0VwpUhD7B4ZP6SzxROsORTGqJKitMEOKL2RnIVAkAzYmXGGZQvE1cQ3c/fOMCV8s5IWPbIaVbOCTqiI3vQ7ktMJma3R33yn0hNgFP7gSsJgaO4HWC6cNkdX84wtWPXvBUMSUQeQyfJhy+kVL4rA8Qyg/UMm77NeiPX210iW+k5Ui/F1wI75LxUgJoVM5aMFrvXVWaT7I8yCkNsNftz3bDL2Hvt1OHL3H+koQGpxkXGtZn1SbdguTC4eM385B98Cqi3g0JfAMx9zEfcpQF4UyMmNKcN1hLdFZ9Sp+cVND53Rb7ffn7GxOzi3eh9hDgttrbKPqE0pgx1gwax93/QMBLli2RDKeZuV1bp/iYBzBc=
        app: barcodelawaretrip
        on:
          repo: Matzy93/ci_workshop
